$HOME/.config/hypr/themes/theme.conf|> $HOME/.config/hypr/themes/colors.conf

# Theme variables
$GTK_THEME = Vanta-Black
$ICON_THEME = Tela-circle-black
$COLOR_SCHEME = prefer-dark
$CURSOR_THEME = Bibata-Modern-Ice
$CURSOR_SIZE = 20
$CODE_THEME = Pure Black

# Apply themes
exec = gsettings set org.gnome.desktop.interface icon-theme '$ICON_THEME'
exec = gsettings set org.gnome.desktop.interface gtk-theme '$GTK_THEME'
exec = gsettings set org.gnome.desktop.interface color-scheme '$COLOR_SCHEME'
exec = Hyde cursor theme '$CURSOR_THEME' size $CURSOR_SIZE
exec = Hyde code theme '$CODE_THEME'

general {
    gaps_in = 5
    gaps_out = 10
    border_size = 1

    # Solid color (no glowing / bouncing effect)
    col.active_border = rgba(888888cc)
    col.inactive_border = rgba(3a3a3ab0)

    resize_on_border = yes
}

decoration {
    rounding = 0

    active_opacity = 0.95
    inactive_opacity = 0.95

    blur {
        enabled = yes
        size = 5
        passes = 4
        ignore_opacity = true
        new_optimizations = true
        xray = false
        noise = 0.0
        popups = true
    }

    dim_inactive = false
    dim_strength = 0.05

    shadow {
        enabled = false
        range = 30
        scale = 2
        render_power = 5
        color = rgba(0f0f0fff)
        color_inactive = rgba(050505ff)
    }
}

group {
    col.border_inactive = rgba(1a1a1ab0)

    # Match active border (no gradient animation)
    col.border_active = rgba(888888cc)

    groupbar {
        col.active = rgba(bfbfbfcc)
        col.inactive = rgba(82828299)
        font_family = JetBrainsMono NFM
        font_size = 10
        text_color = rgba(ffffffff)
    }
}

# Disable border animation completely
animations {
    enabled = yes
    animation = border, 0
}

# Waybar rule
layerrule = unset,waybar