-- Generated by nwg-displays on 2026-08-25 at 21:38:39. Do not edit manually.

hl.monitor({
    output = "eDP-1",
    mode = "1920x1080@60.0",
    position = "0x0",
    scale = 1.5
})
hl.monitor({
    output = "DP-2",
    mode = "1920x1080@240.0",
    position = "1280x0",
    scale = 1.0,
    mirror = "eDP-1"
})
