-- Generated by nwg-displays on 2026-08-21 at 13:37:27. Do not edit manually.

hl.workspace_rule({
    workspace = "1",
    monitor = "eDP-1",
    default = true
})
hl.workspace_rule({
    workspace = "2",
    monitor = "HDMI-A-1",
    default = true
})
